### PR TITLE
Added SVG-icons for bike parking

### PR DESCRIPTION
**Pull request by derdennis**
Dear Steampixel,

thanks a lot for your software!

We wanted to allow wishes for bike parking at the [RadEntscheid Essen Ideenmelder](https://radentscheid-essen.de/ideenmelder/). So we added the letter "P" to the existing icons. 

Maybe other peoples could use these, too? Hopefully @mrmichalzik is okay with these modifications?

Cheers from Essen

Dennis

### CODE REVIEW

**Comment by steampixel** [comment]
Wuhu! First pull request! Thanks so much :-) I think @mrmichalzik is fine with that ;-)

**Comment by steampixel** [comment]
I will also add your URL to the readme file.

**Comment by steampixel** [comment]
I also added your GitHub URL to the credits section. Hope this is OK.

**Comment by derdennis** [comment]
Great, thank you for the merge and the credits! 

Would you also like me to include our new marker types for bike parking wishes in your [`marker.php`](https://github.com/steampixel/RadentscheidWordpressLocations/blob/master/seeds/marker.php)?

**Comment by steampixel** [comment]
Great idea. Added this to my todo list.

**Comment by derdennis** [comment]
Added #24 for the marker types.

**Pull request merged**
